# Generated by Django 4.0.2 on 2022-03-06 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerteam',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_added_customer_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerteam',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_user_modified_customer_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BusnessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=240)),
                ('arabic_type_name', models.CharField(max_length=240)),
                ('other_flag', models.CharField(max_length=1)),
                ('added_datetime', models.DateTimeField(auto_now=True)),
                ('last_modification_datetime', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_added_business_type', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_user_modified_business_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
