# Generated by Django 4.0.3 on 2022-04-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentshift',
            name='slug',
            field=models.SlugField(blank=True, default='zdix7kf222k10y47gn4egf1bdu0h0v-52', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='arabic_type_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='slug',
            field=models.SlugField(blank=True, default='xr240alb10wf00moau27-c77egc4x2jd-4', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='type_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default='gej-0177iss20n00l-x214ac2k3h1frab4', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragent',
            name='slug',
            field=models.SlugField(blank=True, default='ba0k97dafk0ac2v810d204d-2-4r142777', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshift',
            name='slug',
            field=models.SlugField(blank=True, default='70s-c2ot1v2pvvw77-ywv2sb4c0a104bk1', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshiftsattendant',
            name='slug',
            field=models.SlugField(blank=True, default='7e2-0cgbn2c4kn1xhe026xd79p0-c14nub', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercall',
            name='slug',
            field=models.SlugField(blank=True, default='024hc1s4q07vw6b2kuq-210hwjbc7-m02r', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercallparticipant',
            name='slug',
            field=models.SlugField(blank=True, default='pv24la0k74-fv02hm1-oiwb7192x2o0bha', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackage',
            name='slug',
            field=models.SlugField(blank=True, default='072uc-f-09gw0z1z02qov4x2a7t1q4pue1', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackageservice',
            name='slug',
            field=models.SlugField(blank=True, default='616r4024041gu-mz2jty0-77idu2krh320', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='slug',
            field=models.SlugField(blank=True, default='em2b125-i0b2n341l01040-g7t6iw7vsmk', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerteam',
            name='slug',
            field=models.SlugField(blank=True, default='70ez2jz11p20i0bln247spt1e4032-gaw', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customertelecomnumber',
            name='slug',
            field=models.SlugField(blank=True, default='b-wl-2517gj1d4x2nv73ni00tsy41a0af2', null=True, unique=True),
        ),
    ]
