# Generated by Django 4.0.3 on 2022-04-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_agentshift_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentshift',
            name='slug',
            field=models.SlugField(blank=True, default='m1gsf708p05uzrrn-a0n-2tdl02n2164p2', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='slug',
            field=models.SlugField(blank=True, default='rz0su2kk1nx6he2w-29irb40c71bd0-2d0', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default='p20zcji032k287sm112s4zwwd20-b-0vgk', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragent',
            name='slug',
            field=models.SlugField(blank=True, default='1s10c31h2ub4g2i001rm7l2i0q-0qtcj-2', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshift',
            name='slug',
            field=models.SlugField(blank=True, default='yp0-gv92btw-1070m923r2we4pq02101rg', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshiftsattendant',
            name='slug',
            field=models.SlugField(blank=True, default='a8b2i7pdcyd3r-11rx2030a202g407qd0', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercall',
            name='slug',
            field=models.SlugField(blank=True, default='98072t282-i20by1nt06rfg-10t2v0hd4d', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercallparticipant',
            name='slug',
            field=models.SlugField(blank=True, default='00-j4-610j7bk0eljjmf23m0q217b27z32', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackage',
            name='slug',
            field=models.SlugField(blank=True, default='7-2sc4tc320coo0c022b-wka101rohanva', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackageservice',
            name='slug',
            field=models.SlugField(blank=True, default='yi0cdup-p2qtk42-10c12hwf0l7aa20j2z', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='slug',
            field=models.SlugField(blank=True, default='se70i4x20h21pei0h-kj120dm-njo0u2zl', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customerteam',
            name='slug',
            field=models.SlugField(blank=True, default='f1r4h64200nt10p6-21gjl2g2o0c788-2s', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customertelecomnumber',
            name='slug',
            field=models.SlugField(blank=True, default='k24x-10j06x0chsy20dqdiuvw2127vv4-k', null=True, unique=True),
        ),
    ]
