# Generated by Django 4.0.3 on 2022-03-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_businesstype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusnessType',
        ),
    ]
