# Generated by Django 4.0.3 on 2022-03-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_agentshift_slug_businesstype_slug_customer_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentshift',
            name='slug',
            field=models.SlugField(blank=True, default='k8xhohdjemc2fwoxyunj', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='slug',
            field=models.SlugField(blank=True, default='sse4dpydcnhwsh0z679y', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default='utbqfjtqf3swswuf91tv', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragent',
            name='slug',
            field=models.SlugField(blank=True, default='gcna5i35po5wmjj7xvdl', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshift',
            name='slug',
            field=models.SlugField(blank=True, default='x0x7rmvht8h7lsyenfdn', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshiftsattendant',
            name='slug',
            field=models.SlugField(blank=True, default='dtoflhyp3nt5f3ioxp9s', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercall',
            name='slug',
            field=models.SlugField(blank=True, default='vcniduhmxctidvit8upu', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercallparticipant',
            name='slug',
            field=models.SlugField(blank=True, default='jcauw5x47iehz2nuwoa4', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackage',
            name='slug',
            field=models.SlugField(blank=True, default='nxmp4cfnyyurxvc4igz9', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackageservice',
            name='slug',
            field=models.SlugField(blank=True, default='md1teme6mbmrozmj8ffr', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='slug',
            field=models.SlugField(blank=True, default='r11u9strqici1qjdyrcl', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerteam',
            name='slug',
            field=models.SlugField(blank=True, default='hmiugcx5gknhealw9wct', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customertelecomnumber',
            name='slug',
            field=models.SlugField(blank=True, default='i9ckms3slqr4lt4zjnt9', null=True, unique=True),
        ),
    ]
