# Generated by Django 4.0.3 on 2022-04-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_agentshift_slug_alter_businesstype_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentshift',
            name='slug',
            field=models.SlugField(blank=True, default='ukuhafkekj6zjsu1bd3f1003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='slug',
            field=models.SlugField(blank=True, default='mxw788shxscjsz5e96s71003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default='znqfu7jzlxwq2hmdwq0z1003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragent',
            name='slug',
            field=models.SlugField(blank=True, default='xt3n04mpcmywsf5m7qhe1003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshift',
            name='slug',
            field=models.SlugField(blank=True, default='yfjr2a7q8ypixuh8eqo41003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshiftsattendant',
            name='slug',
            field=models.SlugField(blank=True, default='aavtz5ct1r3kvwnwsd5d1003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercall',
            name='slug',
            field=models.SlugField(blank=True, default='nebzbuwq1feltgbjku411003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercallparticipant',
            name='slug',
            field=models.SlugField(blank=True, default='hdppjsit7fslg3ym9oox1003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackage',
            name='slug',
            field=models.SlugField(blank=True, default='a49ll7rsx2zwejapxysg1003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackageservice',
            name='slug',
            field=models.SlugField(blank=True, default='wvv2whqyulewo7ynodnr1003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='slug',
            field=models.SlugField(blank=True, default='qm19kvkpjzgkw7on2hrx1003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerteam',
            name='slug',
            field=models.SlugField(blank=True, default='3hms1qs2jm9ru0jt5i1y1003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customertelecomnumber',
            name='slug',
            field=models.SlugField(blank=True, default='f4cjdib6fhz4p5nyuc0b1003502022-04-02', null=True, unique=True),
        ),
    ]
