# Generated by Django 4.0.3 on 2022-04-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_agentshift_slug_alter_businesstype_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentshift',
            name='slug',
            field=models.SlugField(blank=True, default='kpuqowoehca6xwqx1ufj1137302022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='other_flag',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='slug',
            field=models.SlugField(blank=True, default='829rsxmz0kkylz88b3mu1137302022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default='ka4z9tmbsjgxvhzaoavx1137302022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragent',
            name='slug',
            field=models.SlugField(blank=True, default='cejirilpn8dj9rddz0lg1137302022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshift',
            name='slug',
            field=models.SlugField(blank=True, default='adv5teybcno8nncfyhc41137302022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshiftsattendant',
            name='slug',
            field=models.SlugField(blank=True, default='tu5dt7kz4t1iz8xojjgo1137302022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercall',
            name='slug',
            field=models.SlugField(blank=True, default='dffm4uu5zk7ffl5kjcbl1137302022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercallparticipant',
            name='slug',
            field=models.SlugField(blank=True, default='47sx3pjpeotek2u1ukug1137302022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackage',
            name='slug',
            field=models.SlugField(blank=True, default='nkauhdovtlxloz1ke9kr1137302022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackageservice',
            name='slug',
            field=models.SlugField(blank=True, default='6n0dt6kyjztc1xy5ndco1137302022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='slug',
            field=models.SlugField(blank=True, default='zxgi2uezgdbx3weutpvm1137302022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerteam',
            name='slug',
            field=models.SlugField(blank=True, default='n8z3v9ojlqlylsd0gkgn1137302022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customertelecomnumber',
            name='slug',
            field=models.SlugField(blank=True, default='m6ml969pm5xu5iwcsxdu1137302022-04-02', null=True, unique=True),
        ),
    ]
