# Generated by Django 4.0.3 on 2022-04-06 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_agentshift_slug_alter_businesstype_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentshift',
            name='slug',
            field=models.SlugField(blank=True, default='q2u2u8r47i-9-ok2e306inytt2qi02u100', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='slug',
            field=models.SlugField(blank=True, default='25426b30v7r-jm0wwk0g2m-s1a092onli2', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='business_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.businesstype'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default='200xa1-222a760hn-e24fjkwuxchyu0wdf', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragent',
            name='slug',
            field=models.SlugField(blank=True, default='cu208tv2syag44zk2i2-21200w00c56-ln', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshift',
            name='slug',
            field=models.SlugField(blank=True, default='sw43bd810-el6b2mi2jw-02dcn2000urz2', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshiftsattendant',
            name='slug',
            field=models.SlugField(blank=True, default='09wig20ymhqt2m12026002k49g-go81q-w', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercall',
            name='slug',
            field=models.SlugField(blank=True, default='gsjr60bn0teyc7e40l2-0cb2w1-m2a2tm2', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercallparticipant',
            name='slug',
            field=models.SlugField(blank=True, default='tw-00c44222pmajwiz16-0ujn2be20f025', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackage',
            name='slug',
            field=models.SlugField(blank=True, default='kd24-0w0xpzhchm6c0yc10-22er2g2qn2q', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackageservice',
            name='slug',
            field=models.SlugField(blank=True, default='20-x4jr8z-28x6100y02sruqmum2w2xuot', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='slug',
            field=models.SlugField(blank=True, default='4j64e200ob0ar21z2v4y1c-20c-2ovcnle', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerteam',
            name='slug',
            field=models.SlugField(blank=True, default='xc2ls4sz2j0gh2t201m-15g-j28ra04060', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customertelecomnumber',
            name='slug',
            field=models.SlugField(blank=True, default='22t-d020gsqbr42rnea1-lwj6x09qw22y0', null=True, unique=True),
        ),
    ]
