# Generated by Django 4.0.3 on 2022-04-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_agentshift_slug_alter_businesstype_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentshift',
            name='slug',
            field=models.SlugField(blank=True, default='rzhk204h1u-dlggdvpm42610gy0n321h3', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='slug',
            field=models.SlugField(blank=True, default='3v6ba2mf1400dm5dzk51m-o0ns224ekg3', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(upload_to='customer_logo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default='9wq020-2174k31pfdv57l021jmi0u406-0', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragent',
            name='slug',
            field=models.SlugField(blank=True, default='f1yr4ksto6p02r1v0iz-2f34tdt5ud0x2', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshift',
            name='slug',
            field=models.SlugField(blank=True, default='02ke02y4-6ix10r2y0jrodvml-4d1z3qbf', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshiftsattendant',
            name='slug',
            field=models.SlugField(blank=True, default='p4-w1b-lmmgg2sobqg1clh9410m62023o0', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercall',
            name='slug',
            field=models.SlugField(blank=True, default='0i2zk20v936-oj02zdt01q8j4ww3r145b', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercallparticipant',
            name='slug',
            field=models.SlugField(blank=True, default='8ywwt1d3x4s-1a0-t22kff02194e10tl6n', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackage',
            name='slug',
            field=models.SlugField(blank=True, default='t0hilkmr4-s11y2i0y3ss42e-7620gzqlf', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackageservice',
            name='slug',
            field=models.SlugField(blank=True, default='2ik04dzdk0x4y167h7-02sjdm-13w20jqr', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='slug',
            field=models.SlugField(blank=True, default='f2c01g-20074zm3bs31y40fugv-25ff6y0', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerteam',
            name='slug',
            field=models.SlugField(blank=True, default='01zl-0c92h2vwuo08y5ct143724l-11621', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customertelecomnumber',
            name='slug',
            field=models.SlugField(blank=True, default='310p26bq22140m-74jmz43es04-0r2ipya', null=True, unique=True),
        ),
    ]
