# Generated by Django 4.0.3 on 2022-04-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_agentshift_slug_alter_businesstype_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentshift',
            name='slug',
            field=models.SlugField(blank=True, default='424o-01ws2i40-00i1p43et5u6y2ruzhd5', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='slug',
            field=models.SlugField(blank=True, default='u22vv220pl40-vj4d54mnp0f-n0616pxoz', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='admin_mobile_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default='avd4622-n8vnv400-g4evbhn40xi0fq2g1', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragent',
            name='slug',
            field=models.SlugField(blank=True, default='w1l10m-g42r6f00k2c2j4yv044n-9saltp', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshift',
            name='slug',
            field=models.SlugField(blank=True, default='ms0pgh46e1094-a90zk2w5z0w4z29en42', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshiftsattendant',
            name='slug',
            field=models.SlugField(blank=True, default='4d2nt0i94226o0ux3-24szqq0-obf14y00', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercall',
            name='slug',
            field=models.SlugField(blank=True, default='z4-h0y-y4218ru9q20az700kjfvpc6m248', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercallparticipant',
            name='slug',
            field=models.SlugField(blank=True, default='z-0ed70j4ge20942a0bz48pff4s06y12-t', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackage',
            name='slug',
            field=models.SlugField(blank=True, default='e14j-j46r-qe0e2224dcat4b0500b3x947', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackageservice',
            name='slug',
            field=models.SlugField(blank=True, default='vq-xnpwhee2c10az4n2uk6e00-2p440e1r', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='slug',
            field=models.SlugField(blank=True, default='0klr-fz644m1b4gma0ia06-c1c292p10h2', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerteam',
            name='slug',
            field=models.SlugField(blank=True, default='4q2ok1c301nt240b0-246rzcsco5rzlm0', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customertelecomnumber',
            name='slug',
            field=models.SlugField(blank=True, default='52va4b2jyw07k460usmatik600121-42c', null=True, unique=True),
        ),
    ]
