# Generated by Django 4.0.3 on 2022-04-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_agentshift_slug_alter_businesstype_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentshift',
            name='slug',
            field=models.SlugField(blank=True, default='haqn-x0ea6-092n4229kc4mk0x01dvid4e', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='slug',
            field=models.SlugField(blank=True, default='x1y0l2fzi9v48090e14tq262w6mlb10u', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='added_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default='2d7q-4r0tyck2o000j-odb0413j986hsx2', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragent',
            name='slug',
            field=models.SlugField(blank=True, default='2l40-wr1xxg2rn1xm00m094nsyv-tw6d28', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshift',
            name='slug',
            field=models.SlugField(blank=True, default='02w0041i071l26b9cfzs9u20gutob04-2', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeragentshiftsattendant',
            name='slug',
            field=models.SlugField(blank=True, default='g02ga-p4x2vpe1kyzp00fb4tw-hd692c0g', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercall',
            name='slug',
            field=models.SlugField(blank=True, default='i203v24oht1t6-sz-9r6k2hr9z4x002w10', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercallparticipant',
            name='slug',
            field=models.SlugField(blank=True, default='wzm0w226e2g09urtrx4-010z446ul0la-g', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackage',
            name='slug',
            field=models.SlugField(blank=True, default='x29-4vz4if210mr0-1oxhp4a90620aw0py', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpackageservice',
            name='slug',
            field=models.SlugField(blank=True, default='44fwakx2z1vgl-w010li95-200bkzqi2w6', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='slug',
            field=models.SlugField(blank=True, default='04sbvb2coi-0s254n692bsipp1qe20a10', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerteam',
            name='slug',
            field=models.SlugField(blank=True, default='b-x27nm6z42o9tg0eu12q64vv0uub00rl', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customertelecomnumber',
            name='slug',
            field=models.SlugField(blank=True, default='09jn4-1p-p2jnj22a6w290h8u04pke99o0', null=True, unique=True),
        ),
    ]
