# Generated by Django 4.0.3 on 2022-03-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, default='pqqdmkddetpd0pxxxfu7', null=True, unique=True),
        ),
    ]
