# Generated by Django 4.0.3 on 2022-04-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, default='45302n0t30f14wvu2a6v1c02u8s-yij60', null=True, unique=True),
        ),
    ]
