# Generated by Django 4.0.3 on 2022-04-07 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('address', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telecoms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='9d52o0b0gheln2h5-872k45dv12j2md00', null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('arabic_name', models.CharField(max_length=200)),
                ('priority', models.IntegerField()),
                ('type', models.CharField(choices=[('call_center', 'Call Center'), ('communication', 'Communication')], max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active'), ('deleted', 'Deleted')], max_length=20)),
                ('price', models.DecimalField(decimal_places=10, max_digits=12)),
                ('grace', models.BooleanField(blank=True, null=True)),
                ('grace_period_day', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('discount_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.currency')),
                ('telecom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telecoms.telecomoperator')),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='7bf22ojg58-17m3-004vhpnxajg3u20ug5', null=True, unique=True)),
                ('subtype_value', models.FloatField()),
                ('index', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('status', models.BooleanField()),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='address.currency')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.package')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.service')),
            ],
            options={
                'db_table': 'package_service',
            },
        ),
        migrations.CreateModel(
            name='PackageBillingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='jg827-sg04hfgbng02op50m2al5v41-b0n', null=True, unique=True)),
                ('serial', models.IntegerField()),
                ('billing_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annually', 'Semi Annually'), ('annually', 'Annually')], max_length=200)),
                ('percentage_added_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('added_datetime', models.DateTimeField(auto_now=True)),
                ('last_modification_datetime', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_added_package_billing_type', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_user_modified_package_billing', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
            options={
                'db_table': 'package_billing_type',
            },
        ),
    ]
