# Generated by Django 4.0.2 on 2022-02-09 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('address', '0002_alter_city_added_by_alter_city_last_modified_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telecoms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('arabic_name', models.CharField(max_length=200)),
                ('priority', models.IntegerField()),
                ('type', models.CharField(choices=[('call_center', 'Call Center'), ('communication', 'Commuinication')], max_length=80)),
                ('status', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=12)),
                ('grace', models.BooleanField()),
                ('grace_period_day', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('discount_price', models.DecimalField(decimal_places=10, max_digits=12)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.currency')),
                ('telecom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telecoms.telecomoperator')),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype_value', models.FloatField()),
                ('index', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=10, max_digits=12)),
                ('status', models.BooleanField()),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='address.currency')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.package')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.service')),
            ],
            options={
                'db_table': 'package_service',
            },
        ),
        migrations.CreateModel(
            name='PackageBillingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('billing_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annually', 'Semi Annually'), ('annually', 'Annually')], max_length=200)),
                ('percentage_added_price', models.DecimalField(decimal_places=10, max_digits=12)),
                ('added_datetime', models.DateTimeField(auto_now=True)),
                ('last_modification_datetime', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_added_package_billing_type', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_user_modified_package_billing', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
            options={
                'db_table': 'package_billing_type',
            },
        ),
    ]
