# Generated by Django 4.0.3 on 2022-03-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, default='syqacwlskgpjonk06wuh', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='packagebillingtype',
            name='slug',
            field=models.SlugField(blank=True, default='mzr47xankexo5vtf13l4', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='packageservice',
            name='slug',
            field=models.SlugField(blank=True, default='7et05ok8zm42cx8w4pzp', null=True, unique=True),
        ),
    ]
