# Generated by Django 4.0.3 on 2022-04-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, default='0m8r0c713fm812ru4xx7zecck-2c-g220u', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='packagebillingtype',
            name='slug',
            field=models.SlugField(blank=True, default='3zgm2y10kueh87502xple2m082-714ph7', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='slug',
            field=models.SlugField(blank=True, default='72-z0r10yi0l15yozni-j722srqdb3024v', null=True, unique=True),
        ),
    ]
