# Generated by Django 4.0.3 on 2022-04-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_slug_alter_packagebillingtype_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, default='cxw8keadjbqkyeuijhdo1003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='packagebillingtype',
            name='slug',
            field=models.SlugField(blank=True, default='eovqpjamrcekpeblstga1003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='slug',
            field=models.SlugField(blank=True, default='lkr2ltiht6iqnlpxk2d21003502022-04-02', null=True, unique=True),
        ),
    ]
