# Generated by Django 4.0.3 on 2022-04-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_package_slug_alter_packagebillingtype_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='grace',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='grace_period_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, default='phuezih3o45p9nydczi21307562022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('call_center', 'Call Center'), ('communication', 'Communication')], max_length=80),
        ),
        migrations.AlterField(
            model_name='packagebillingtype',
            name='slug',
            field=models.SlugField(blank=True, default='zytkjwqwiqaewogyf1be1307562022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='slug',
            field=models.SlugField(blank=True, default='hf7puqyry0qgkrmktfie1307562022-04-02', null=True, unique=True),
        ),
    ]
