# Generated by Django 4.0.3 on 2022-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_alter_package_grace_alter_package_grace_period_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='discount_price',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, default='dx07mjol5k0pxu3mbqoo1312002022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='packagebillingtype',
            name='slug',
            field=models.SlugField(blank=True, default='k4wmupaemaglju0nhb2t1312002022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='slug',
            field=models.SlugField(blank=True, default='xj6lew4dmys7e2jvtejj1312002022-04-02', null=True, unique=True),
        ),
    ]
