# Generated by Django 4.0.3 on 2022-04-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_alter_package_discount_alter_package_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, default='yuz7ghykr3nruuqpuz111315322022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='packagebillingtype',
            name='percentage_added_price',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='packagebillingtype',
            name='slug',
            field=models.SlugField(blank=True, default='ifgwvb9wg55icxmi0lrh1315322022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='slug',
            field=models.SlugField(blank=True, default='yidpzazdudzlv05pouzt1315322022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='total_price',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
