# Generated by Django 4.0.3 on 2022-04-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_alter_package_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, default='o4r4rqkw06-g2n6f7q4n0232r011-nnv94kc', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active'), ('deleted', 'Deleted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='packagebillingtype',
            name='slug',
            field=models.SlugField(blank=True, default='7y04m7co1402k-68a3rg24pcz-ovv5a20k4w', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='slug',
            field=models.SlugField(blank=True, default='ef2u6ac240qc443-av02-yw142y0ch17m5r1', null=True, unique=True),
        ),
    ]
