# Generated by Django 4.0.3 on 2022-04-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_alter_package_slug_alter_package_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, default='4614n231me2or1kad0r0u-h30exjn227n', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='packagebillingtype',
            name='slug',
            field=models.SlugField(blank=True, default='q46120c-z04u4vu-vfn2a4zjk3ato2z10l', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='slug',
            field=models.SlugField(blank=True, default='4v016su1mrod2y4ttaj4z-3w1-0dj202br', null=True, unique=True),
        ),
    ]
