# Generated by Django 4.0.3 on 2022-04-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='j4c2-o80d-2bla012l20r5kmyjhg7tn50a', null=True, unique=True)),
                ('name', models.CharField(max_length=145)),
                ('arabic_name', models.CharField(max_length=145)),
                ('access_code', models.IntegerField()),
                ('added_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('last_modification_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active'), ('deleted', 'Deleted')], max_length=20)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='x-a5csk604qj2ru1xal2tzcua7g805-20m', null=True, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('arabic_name', models.CharField(max_length=100)),
                ('access_code', models.IntegerField()),
                ('is_service_country', models.BooleanField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active'), ('suspended', 'Suspended'), ('on_hold', 'On Hold')], max_length=20)),
                ('added_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modification_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='5rp-e25s1zl0b3qu-7f0s3e2onga4028f0', null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('arabic_symbol', models.CharField(max_length=10)),
                ('decimal_digits_number', models.DecimalField(decimal_places=8, max_digits=9)),
                ('added_datetime', models.DateTimeField(auto_now=True)),
                ('last_modification_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='azy978c5yo8xpq9332-g202x05741e0l-8', null=True, unique=True)),
                ('name', models.CharField(max_length=145)),
                ('arabic_name', models.CharField(max_length=145)),
                ('status', models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active'), ('deleted', 'Deleted')], max_length=20)),
                ('added_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modification_datetime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='9zzfi7rzag7bi-40j1hm-f82dk0f550022', null=True, unique=True)),
                ('added_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('last_modification_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active'), ('deleted', 'Deleted')], max_length=20)),
            ],
            options={
                'db_table': 'user_country',
            },
        ),
    ]
