# Generated by Django 4.0.1 on 2022-01-22 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('arabic_name', models.CharField(max_length=100)),
                ('access_code', models.IntegerField()),
                ('is_service_country', models.BooleanField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active'), ('suspended', 'Suspended'), ('on_hold', 'On Hold')], max_length=20)),
                ('added_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modification_datetime', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=145)),
                ('arabic_name', models.CharField(max_length=145)),
                ('status', models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active'), ('deleted', 'Deleted')], max_length=20)),
                ('added_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modification_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.country')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=145)),
                ('arabic_name', models.TextField()),
                ('access_code', models.IntegerField()),
                ('added_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('last_modification_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adding_user', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.state')),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
