# Generated by Django 4.0.3 on 2022-04-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, default='a422k79j2dj07w0t-1lxmuyia0463dov9', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='arabic_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, default='6o-zs10-b4s4u9x2upflc07kf72lvsh02q', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='slug',
            field=models.SlugField(blank=True, default='4tomta0-1hqry9elmt20zozt0k27x642j', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, default='62b7p0ryqk624-ysi1wanors0r2b849-x0', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usercountry',
            name='slug',
            field=models.SlugField(blank=True, default='2zj70k2l6oow10dam2-p4o8940o0k-yzbv', null=True, unique=True),
        ),
    ]
