# Generated by Django 3.2.11 on 2022-03-01 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0002_alter_city_added_by_alter_city_last_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='arabic_name',
            field=models.CharField(max_length=145),
        ),
        migrations.AlterField(
            model_name='state',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_added_state', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='state',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_user_modified_state', to=settings.AUTH_USER_MODEL),
        ),
    ]
