# Generated by Django 4.0.2 on 2022-02-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_city_added_by_alter_city_last_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='arabic_name',
            field=models.CharField(max_length=145),
        ),
    ]
