# Generated by Django 4.0.2 on 2022-03-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_city_arabic_name'),
        ('address', '0003_auto_20220301_0614'),
    ]

    operations = [
    ]
