# Generated by Django 4.0.2 on 2022-03-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_merge_20220301_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, default='w50lxdjzr9zzd2vwg3dx', null=True, verbose_name='State Slug'),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, default='l1vbueiwvrjyzd5itvjp', null=True, verbose_name='State Slug'),
        ),
        migrations.AddField(
            model_name='currency',
            name='slug',
            field=models.SlugField(blank=True, default='gmskbpsdg5kac1rja7cy', null=True, verbose_name='State Slug'),
        ),
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, default='j9smj6fiaus7cxpciydo', null=True, verbose_name='State Slug'),
        ),
        migrations.AddField(
            model_name='usercountry',
            name='slug',
            field=models.SlugField(blank=True, default='fjpljhbj5avvfcu8oac1', null=True, verbose_name='State Slug'),
        ),
    ]
