# Generated by Django 4.0.2 on 2022-03-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_city_slug_country_slug_currency_slug_state_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, default='ls8cyxesrpwuxd2l8ooy', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, default='jeldqeifnfzotpoblz47', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='slug',
            field=models.SlugField(blank=True, default='kpzra6uioijd13nys1mf', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, default='5qrmpfqcx3tj8bbpg4u0', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usercountry',
            name='slug',
            field=models.SlugField(blank=True, default='8qfg9auevqax7a60ar0b', null=True, unique=True),
        ),
    ]
