# Generated by Django 4.0.3 on 2022-03-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_country_last_modified_by_alter_city_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, default='vuyjgdui4gclwzavrqlu', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, default='zydtcakk6wl3c3geqfst', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='slug',
            field=models.SlugField(blank=True, default='4jxbrujfcab3huiddtyu', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, default='9pigvhcgu5yox2oipjxd', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usercountry',
            name='slug',
            field=models.SlugField(blank=True, default='3itcfeffzprztap7yo7o', null=True, unique=True),
        ),
    ]
