# Generated by Django 4.0.3 on 2022-04-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_alter_city_slug_alter_country_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, default='p252eny8tydwzm3amafh1003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active'), ('deleted', 'Deleted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, default='01rjtv1pltah125e6sz01003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='slug',
            field=models.SlugField(blank=True, default='pcopftqvxw45nstvfdna1003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, default='lypapi9lw7asaqxzat9f1003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usercountry',
            name='slug',
            field=models.SlugField(blank=True, default='kisdaagjnywoba3xhnn41003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usercountry',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active'), ('deleted', 'Deleted')], max_length=20),
        ),
    ]
