# Generated by Django 4.0.3 on 2022-04-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0009_alter_city_slug_alter_city_status_alter_country_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, default='p2xxj1ifh70y0s-x3d0678p-1gi4022k4s', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, default='pq4kuys34p61-0s221oaai02zv027d-d1e', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='slug',
            field=models.SlugField(blank=True, default='ox2jcc02qu-d0k3h4k1w60edwc24ok-1s6', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, default='5202d-409gl3j0s-p1142pvorcv063cjd7', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usercountry',
            name='slug',
            field=models.SlugField(blank=True, default='z44124-b21092ew03wn02-vm2qxoxtn6jq', null=True, unique=True),
        ),
    ]
