# Generated by Django 4.0.3 on 2022-03-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, default='9l5v5q7wbywumarapny8', null=True, unique=True),
        ),
    ]
