# Generated by Django 4.0.3 on 2022-04-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, default='b8z9adlbbaspysqavdog1003502022-04-02', null=True, unique=True),
        ),
    ]
