# Generated by Django 4.0.3 on 2022-04-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, default='246cqtpp2kv5c-e-o1n6l0m01qs32l4t0p', null=True, unique=True),
        ),
    ]
