# Generated by Django 4.0.3 on 2022-04-07 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelecomOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='9so-6-o22mn90o275izh550dtcb0ck14j8', null=True, unique=True)),
                ('currency_code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active'), ('deleted', 'Deleted')], max_length=40)),
                ('logo', models.ImageField(upload_to='telecom_logo', verbose_name='logo')),
                ('last_modification_datetime', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_added_telecom_operator', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_user_modified_telecom_operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telecom_operator',
            },
        ),
        migrations.CreateModel(
            name='TelecomNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='i82d2u505u1m05ks4520j-5-h7aitwh2aj', null=True, unique=True)),
                ('number', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('fix_line', 'Fix-Line'), ('short_code4', 'Short-Code4'), ('short_code5', 'Short-Code5'), ('short_code6', 'Short-Code6'), ('mobile', 'Mobile')], max_length=80)),
                ('added_datetime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('taken', 'Taken'), ('withdraw', 'Withdraw')], max_length=60)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_added_telecom_number', to=settings.AUTH_USER_MODEL)),
                ('telecom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telecoms.telecomoperator')),
            ],
            options={
                'db_table': 'telecom_number',
            },
        ),
    ]
