# Generated by Django 4.0.3 on 2022-03-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecoms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecomnumber',
            name='slug',
            field=models.SlugField(blank=True, default='t1em0qghtlxhhliccw0g', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='telecomoperator',
            name='slug',
            field=models.SlugField(blank=True, default='yi7kmifz9h9d9q6sy1vf', null=True, unique=True),
        ),
    ]
