# Generated by Django 4.0.3 on 2022-03-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecoms', '0002_telecomnumber_slug_telecomoperator_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomnumber',
            name='slug',
            field=models.SlugField(blank=True, default='gveg3vztsizhijbt3chd', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='telecomoperator',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='telecomoperator',
            name='slug',
            field=models.SlugField(blank=True, default='n50plbl3ermoh382zpat', null=True, unique=True),
        ),
    ]
