# Generated by Django 4.0.3 on 2022-03-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecoms', '0003_alter_telecomnumber_slug_alter_telecomoperator_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomnumber',
            name='slug',
            field=models.SlugField(blank=True, default='6bbzepkt9smrbljzeomj', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='telecomoperator',
            name='slug',
            field=models.SlugField(blank=True, default='llaxf7itsd80c8pzrmej', null=True, unique=True),
        ),
    ]
