# Generated by Django 4.0.3 on 2022-04-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecoms', '0004_alter_telecomnumber_slug_alter_telecomoperator_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomnumber',
            name='slug',
            field=models.SlugField(blank=True, default='0swceu7ghnylelx1qyi41003502022-04-02', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='telecomoperator',
            name='slug',
            field=models.SlugField(blank=True, default='wfxsdb55bw4tjl4lsfj51003502022-04-02', null=True, unique=True),
        ),
    ]
