# Generated by Django 4.0.3 on 2022-04-06 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telecoms', '0005_alter_telecomnumber_slug_alter_telecomoperator_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecomnumber',
            name='telecom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telecoms.telecomoperator'),
        ),
        migrations.AlterField(
            model_name='telecomnumber',
            name='slug',
            field=models.SlugField(blank=True, default='6l22w6b-g6czl4d0m2zt0os0-riy6010vn', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='telecomoperator',
            name='slug',
            field=models.SlugField(blank=True, default='balv2d262o0b6084aueb0-1g10nv-h5b0g', null=True, unique=True),
        ),
    ]
