# Generated by Django 4.0.3 on 2022-04-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecoms', '0006_telecomnumber_telecom_alter_telecomnumber_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomnumber',
            name='slug',
            field=models.SlugField(blank=True, default='4h2sw26rsp40ytqi1s0i3og0wn2m7-c01', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='telecomoperator',
            name='logo',
            field=models.ImageField(upload_to='telecom_logo', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='telecomoperator',
            name='slug',
            field=models.SlugField(blank=True, default='x-324ewmp01l02x2v8-164449jwnx0yjt0', null=True, unique=True),
        ),
    ]
