# Generated by Django 4.0.3 on 2022-04-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('slug', models.SlugField(blank=True, default='1oy7ay02lzl07y8p-42jmw0-25kk2vksx5', null=True, unique=True)),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=150, verbose_name='Second Name')),
                ('third_name', models.CharField(max_length=150, verbose_name='Third Name')),
                ('fourth_name', models.CharField(max_length=150, verbose_name='Fourth Name')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='User Name')),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('customer_administrator', 'Administrator Customer'), ('agent', 'Agent'), ('team_leader', 'Team Leader'), ('administrator', 'Administrator'), ('special_administrator', 'Special Administrator'), ('monitor', 'Monitor')], default='customer', max_length=100, verbose_name='User Type')),
                ('user_status', models.CharField(choices=[('first_login', 'First Login'), ('active', 'Active'), ('not_active', 'Not Active'), ('suspended', 'Suspended'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], default='first_login', max_length=100, verbose_name='User Status')),
                ('phone_number', models.CharField(max_length=100, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('registration_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
