# Generated by Django 4.0 on 2022-01-12 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=150, verbose_name='Second Name')),
                ('third_name', models.CharField(max_length=150, verbose_name='Third Name')),
                ('fourth_name', models.CharField(max_length=150, verbose_name='Fourth Name')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='User Name')),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('customer_administrator', 'Administrator Customer'), ('agent', 'Agent'), ('team_leader', 'Team Leader'), ('administrator', 'Administrator'), ('special_administrator', 'Special Administrator'), ('monitor', 'Monitor')], max_length=100, verbose_name='User Type')),
                ('user_status', models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active'), ('suspended', 'Suspended'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], max_length=100, verbose_name='User Status')),
                ('phone_number', models.CharField(max_length=100, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('registration_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
