# Generated by Django 4.0 on 2022-01-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('customer_administrator', 'Administrator Customer'), ('agent', 'Agent'), ('team_leader', 'Team Leader'), ('administrator', 'Administrator'), ('special_administrator', 'Special Administrator'), ('monitor', 'Monitor')], default='first_login', max_length=100, verbose_name='User Type'),
        ),
    ]
