# Generated by Django 4.0 on 2022-01-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('first_login', 'First Login'), ('active', 'Active'), ('not_active', 'Not Active'), ('suspended', 'Suspended'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], default='first_login', max_length=100, verbose_name='User Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('customer_administrator', 'Administrator Customer'), ('agent', 'Agent'), ('team_leader', 'Team Leader'), ('administrator', 'Administrator'), ('special_administrator', 'Special Administrator'), ('monitor', 'Monitor')], default='customer', max_length=100, verbose_name='User Type'),
        ),
    ]
