# Generated by Django 4.0.3 on 2022-04-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, default='aghdm2mhzk6am4cuoywm1003502022-04-02', null=True, unique=True),
        ),
    ]
